version: '3.4'
services:
  darts_score:
    container_name: darts_score_client
    build:
      context: .
      target: development
    ports:
     - "3000:3000"
    volumes:
     - ./public:/app/public
     - ./src:/app/src
     - ./package.json:/app/package.json
    env_file:
      - ./.env
    tty: true
    environment:
      NODE_ENV: "development"
  # darts_score:
  #   container_name: darts_score_client
  #   build:
  #     context: .
  #     target: production
  #   ports:
  #    - "3000:80"
  #   tty: true
  #   environment:
  #     - DARTS_SCORE_API_URL=${VITE_API_URL}